In [73]:
import numpy as np

## Question 1: Numpy

#### (A) Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print bar and its shape.

In [74]:
foo = np.arange(0,30,1,dtype=int) #foo declaration
#(arange is half open, we need to put 30 as upper bound)
print("Printing type(foo):", type(foo)) #confirming its a numpy array
print("Printing foo:" , foo) #printing 1D array
print("Printing foo shape using .shape:", foo.shape) #confirming 1D
print("Printing type(shape):", type(foo.shape))

Printing type(foo): <class 'numpy.ndarray'>
Printing foo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Printing foo shape using .shape: (30,)
Printing type(shape): <class 'tuple'>



#### (B) Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [75]:
bar = foo.reshape((5,6)) #creating bar(5x6)(2D) from 1D foo
print("Printing type(bar):", type(bar))
print("Printing bar:") #confirming reshape worked
print(bar) 
print("Printing bar shape using .shape:", bar.shape) #confirming 5x6
print("Printing type(shape):", type(bar.shape))

Printing type(bar): <class 'numpy.ndarray'>
Printing bar:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Printing bar shape using .shape: (5, 6)
Printing type(shape): <class 'tuple'>


#### (C) Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [76]:
baz = bar.reshape((5,3,2)) #creating bar(5x3x2)(3D) from 2D bar
print("Printing type(baz):", type(baz))
print("Printing baz:") #confirming reshape worked
print(baz) 
print("Printing baz shape using .shape:", baz.shape) #confirming 5x3x2
print("Printing type(shape):", type(baz.shape))

Printing type(baz): <class 'numpy.ndarray'>
Printing baz:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]
Printing baz shape using .shape: (5, 3, 2)
Printing type(shape): <class 'tuple'>


#### (D) There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)


In [77]:
print("Printing bar:")
print(bar) 
print("Original value of col 1 row 2:",bar[1][0])
print("Coordinates of col 1 row 2: 1,0")
bar[1][0] = -1 #update [1,0] with new value
print("Printing updated bar:") #confirming value got updated
print(bar) 
print("Printing foo:") #checking foo
print(foo)
print("Printing baz:") #checking baz
print(baz) 
print()
print()
print()
print("In conclusion, updating [1,0] in bar was successful. Updating this value changed foo[6] and baz[1,0,0] automatically, which means that reshape returns a view.")

Printing bar:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Original value of col 1 row 2: 6
Coordinates of col 1 row 2: 1,0
Printing updated bar:
[[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Printing foo:
[ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Printing baz:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[-1  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]



In conclusion, updating [1,0] in bar was successful. Updating this value changed foo[6] and baz[1,0,0] automatically, which means that reshape returns a view.


#### (E) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:

(i) Sum baz over its second dimension and print the result.

In [78]:
print(np.sum(baz, axis=1)) #2nd dimension is axis 1, counting from 0

[[ 6  9]
 [17 27]
 [42 45]
 [60 63]
 [78 81]]


(ii) Sum baz over its first dimension and print the result.

In [79]:
print(np.sum(baz, axis=0)) #1st dimension is axis 0

[[53 65]
 [70 75]
 [80 85]]


(iii) Sum baz over both its first and third dimensions and print the result.


In [80]:
print(np.sum(baz, axis=(0,2))) #passing a tuple to the axis parameter to sum both 1st and 3rd dimension

[118 145 165]



#### (F) Along with shaping and indexing, we also do a lot of slicing, which is where you index with ranges to get subvectors and submatrices. Write code to do the following:

(i) Slice out the second row of bar and print it.

In [ ]:
bar #preview original

array([[ 0,  1,  2,  3,  4,  5],
       [-1,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
bar[1] #2nd row

array([-1,  7,  8,  9, 10, 11])

(ii) Slice out the last two columns of bar using the -1 notation and print it.

In [101]:
print(bar[:, -2:]) #negative iterates through from the end

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


(iii) Reshape bar into the right 2×3 submatrix format and print it.

In [106]:
print(bar[3:5, 0:3])

[[18 19 20]
 [24 25 26]]
