In [73]:
import numpy as np

## Question 1: Numpy

#### (A) Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print bar and its shape.

In [74]:
foo = np.arange(0,30,1,dtype=int) #foo declaration
#(arange is half open, we need to put 30 as upper bound)
print("Printing type(foo):", type(foo)) #confirming its a numpy array
print("Printing foo:" , foo) #printing 1D array
print("Printing foo shape using .shape:", foo.shape) #confirming 1D
print("Printing type(shape):", type(foo.shape))

Printing type(foo): <class 'numpy.ndarray'>
Printing foo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Printing foo shape using .shape: (30,)
Printing type(shape): <class 'tuple'>



#### (B) Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [75]:
bar = foo.reshape((5,6)) #creating bar(5x6)(2D) from 1D foo
print("Printing type(bar):", type(bar))
print("Printing bar:") #confirming reshape worked
print(bar) 
print("Printing bar shape using .shape:", bar.shape) #confirming 5x6
print("Printing type(shape):", type(bar.shape))

Printing type(bar): <class 'numpy.ndarray'>
Printing bar:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Printing bar shape using .shape: (5, 6)
Printing type(shape): <class 'tuple'>


#### (C) Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [76]:
baz = bar.reshape((5,3,2)) #creating bar(5x3x2)(3D) from 2D bar
print("Printing type(baz):", type(baz))
print("Printing baz:") #confirming reshape worked
print(baz) 
print("Printing baz shape using .shape:", baz.shape) #confirming 5x3x2
print("Printing type(shape):", type(baz.shape))

Printing type(baz): <class 'numpy.ndarray'>
Printing baz:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]
Printing baz shape using .shape: (5, 3, 2)
Printing type(shape): <class 'tuple'>


#### (D) There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)


In [77]:
print("Printing bar:")
print(bar) 
print("Original value of col 1 row 2:",bar[1][0])
print("Coordinates of col 1 row 2: 1,0")
bar[1][0] = -1 #update [1,0] with new value
print("Printing updated bar:") #confirming value got updated
print(bar) 
print("Printing foo:") #checking foo
print(foo)
print("Printing baz:") #checking baz
print(baz) 
print()
print()
print()
print("In conclusion, updating [1,0] in bar was successful. Updating this value changed foo[6] and baz[1,0,0] automatically, which means that reshape returns a view.")

Printing bar:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Original value of col 1 row 2: 6
Coordinates of col 1 row 2: 1,0
Printing updated bar:
[[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Printing foo:
[ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Printing baz:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[-1  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]



In conclusion, updating [1,0] in bar was successful. Updating this value changed foo[6] and baz[1,0,0] automatically, which means that reshape returns a view.


#### (E) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:

(i) Sum baz over its second dimension and print the result.

In [78]:
print(np.sum(baz, axis=1)) #2nd dimension is axis 1, counting from 0

[[ 6  9]
 [17 27]
 [42 45]
 [60 63]
 [78 81]]


(ii) Sum baz over its first dimension and print the result.

In [79]:
print(np.sum(baz, axis=0)) #1st dimension is axis 0

[[53 65]
 [70 75]
 [80 85]]


(iii) Sum baz over both its first and third dimensions and print the result.


In [80]:
print(np.sum(baz, axis=(0,2))) #passing a tuple to the axis parameter to sum both 1st and 3rd dimension

[118 145 165]



#### (F) Along with shaping and indexing, we also do a lot of slicing, which is where you index with ranges to get subvectors and submatrices. Write code to do the following:

(i) Slice out the second row of bar and print it.

In [81]:
bar #preview original

array([[ 0,  1,  2,  3,  4,  5],
       [-1,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [88]:
bar[1] #2nd row

array([-1,  7,  8,  9, 10, 11])

(ii) Slice out the last two columns of bar using the -1 notation and print it.

In [101]:
print(bar[:, -2:]) #negative iterates through from the end

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


(iii) Reshape bar into the right 2×3 submatrix format and print it.

In [106]:
print(bar[3:5, 0:3])

[[18 19 20]
 [24 25 26]]


## Question 2
Imagine that you have an old-fashioned balance scale as shown below.

You have five objects of unknown mass m1,m2,m3,m4,m5m1​,m2​,m3​,m4​,m5​. You would like to find the mass of each of these objects using the scale. If you put one or more of the objects on each side of the scale, you will be able to measure the difference in weight. This scale does not work, however, if one side is left empty.

(A) You make a measurement of objects {1,2}{1,2} against objects {3,4}{3,4} and get a difference of 1kg. Write this as a linear equation for the masses.

**_Answer:_**

(m₁ + m₂) − (m₃ + m₄) = 1

(B) What is the minimum number of such measurements necessary to recover all five masses?

**_Answer:_**

This is a system of linear equations.

This system has 5 variables (m₁ to m₅). Therefore 5 unique measurements will provide 5 equations similar to the one listed in (A). 

These equations can be solved together to provide the values.

(C) If the answer to the above question is NN, come up with N−1N−1 measurements that, when combined with the answer to (A) above, would make it possible to recover the masses.

**_Answer:_**

**Given:** (m₁ + m₂) − (m₃ + m₄) = 1

Additional required equations:
1. (m₁ + m₃) - (m₂ + m₅) = a

2. (m₂ + m₄) - (m₃ + m₅) = b

3. (m₁ + m₄) - (m₂ + m₃) = c

4. (m₁ + m₅) - (m₃ + m₄) = d


(D) What would AA and bb be in the matrix form of the linear system corresponding to the NN measurements?
That is, if you were to set this up as Am=bAm=b where mm is the vector of unknown masses. Denote the result of the ii-th measurement as bibi​. (Typeset these using the bmatrix environment.)

**_Answer:_**

Am=b

Based on the coefficients in the 5 linear equations, we can derive A to be:

$$
\begin{array}{c|ccccc}
   & m_1 & m_2 & m_3 & m_4 & m_5  \\
\hline
\text{Eqn 1} & 1  & 1  & -1  & -1  & 0  \\
\text{Eqn 2} & 1  & 0  & 1  & 0  & -1  \\
\text{Eqn 3} & 0  & 1  & -1  & 1  & -1  \\
\text{Eqn 4} & 1  & -1  & -1  & 1  & 0  \\
\text{Eqn 5} & 1  & 0  & -1  & -1  & 1  
\end{array}
$$


Similarly,  

$$
m =
\begin{bmatrix}
m_1 \\
m_2 \\
m_3 \\
m_4 \\
m_5
\end{bmatrix}
$$   

$$
B =
\begin{bmatrix}
1 \\
a \\
b \\
c \\
d
\end{bmatrix}
$$  


Thus the final equation is:




$$
\begin{bmatrix}
1  & 1  & -1  & -1  & 0  \\
1  & 0  & 1  & 0  & -1  \\
0  & 1  & -1  & 1  & -1  \\
1  & -1  & -1  & 1  & 0  \\
1  & 0  & -1  & -1  & 1  
\end{bmatrix}
\begin{bmatrix}
m_1 \\
m_2 \\
m_3 \\
m_4 \\
m_5
\end{bmatrix}
=
\begin{bmatrix}
1 \\
a \\
b \\
c \\
d
\end{bmatrix}
$$

This linear system can be solved to determine the unknown masses.

## Question 3
Fairly often in machine learning and other disciplines that use linear algebra to formalize computational problems, you see explicit matrix inverses like A−1bA−1b in papers and books. Of course, you learn in linear algebra classes how to perform such an inverse, and in the NumPy linear algebra library you’ll see a function that will compute the inverse. It seems sensible right? And it’s right there on the page: Invert the matrix A and then multiply by the vector b. How hard can it be?

Well… don’t do that. When you see A−1bA−1b you should read that as “the x that is the result of solving the linear system Ax=bAx=b”. You should use something like the solve function in the NumPy linear algebra package. If you have to solve multiple such systems with the same matrix, you might think about performing an LU decomposition, a topic we’ll return to in a couple of weeks.

The issue is one of numerical stability, which boils down to the fact that 1) floating point numbers on computers don’t have infinite precision, and 2) some quantities (e.g., infinite sums or numerical integrals) require us to truncate and approximate if we want the computation to complete. These issues are deep and this course won’t delve into them significantly. However, the “explicit inverse” issue is worth looking at just to see an example.
(A)

A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector [x1,x2,...,xN]T[x1​,x2​,...,xN​]T, then the associated (square) Vandermonde matrix would be
V=[1x1x12x13…x1N−11x2x22x23…x2N−1⋮⋮⋮⋮…⋮1xNxN2xN3…xNN−1]
V=
​11⋮1​x1​x2​⋮xN​​x12​x22​⋮xN2​​x13​x23​⋮xN3​​…………​x1N−1​x2N−1​⋮xNN−1​​
​

Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector [1,2,...,N]T[1,2,...,N]T for any NN. Do it without using a loop. Here’s a stub to get you started:

def vandermonde(N):
    vec = np.arange(N) + 1
    # Finish me.

Use your function for N=12N=12, store it in variable vander, and print the result.
(B)

Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.
(C)

First, solve the linear system the naïve way, pretending like you don’t know xx. Import numpy.linalg, invert VV and multiply it by bb. Print out your result. What should you get for your answer? If the answer is different than what you expected, write some code to print out that difference.
(D)

Now solve the linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?